Zh2En_Settings = {}
Zh2En_Data = {}
Zh2En_Settings["init"] = false
Zh2En_LastQueryResult = ";)"
Zh2En_NotFoundMessage = "没有找到对应的英文 :(\n\n" ..
  "你可以告诉我以帮助完善这个插件\n\n" ..
  "|cffF0A90FKronos |cffff0000部落\n\n" ..
  "|cffFFF569Froki |cff00ff00<Original Dream>\n\n" ..
  "|cffffffffQQ群: 454368842\n\n" ..
  "谢谢"

function Zh2En_onLoad()
  this:RegisterEvent("ADDON_LOADED")
  Zh2En_addMessage("项目地址: https://github.com/x1a0/vanilla-wow-addons")
end

function Zh2En_onEvent()
  if ((event == "ADDON_LOADED") and (arg1 == "Zh2En")) then
    if (not Zh2En_Settings["init"]) then
      Zh2En_InitData()
      Zh2En_Settings["init"] = true
    end
  end
end

function Zh2En_addMessage(msg)
  DEFAULT_CHAT_FRAME:AddMessage("<Zh2En> " .. msg)
end

StaticPopupDialogs["ZH2EN_FOUND"] = {
  text = "%s",
  button2 = "OK",
  timeout = 0,
  whileDead = true,
  hideOnEscape = 1,
  preferredIndex = 3,
  hasEditBox = 1,
  enterClicksFirstButton = 1,
  OnShow = function()
    getglobal(this:GetName().."EditBox"):SetText(Zh2En_LastQueryResult);
  end
};

StaticPopupDialogs["ZH2EN_NOT_FOUND"] = {
  text = Zh2En_NotFoundMessage,
  button2 = "OK",
  timeout = 0,
  whileDead = true,
  hideOnEscape = 1,
  preferredIndex = 4
};

SLASH_ZH2EN1 = '/z2e'
function SlashCmdList.ZH2EN(msg, editbox)
  Zh2En_LastQueryResult = Zh2En_Data[msg]
  if (Zh2En_LastQueryResult) then
    StaticPopup_Show("ZH2EN_FOUND", msg)
  else
    StaticPopup_Show("ZH2EN_NOT_FOUND", msg)
  end
end

function Zh2En_InitData()
  -- 副本
  Zh2En_Data["血色修道院"] = "Scarlet Monestary (SM)"
  Zh2En_Data["血色"] = "Scarlet Monestary (SM)"
  Zh2En_Data["斯坦索姆"] = "Stratholme (STR)"
  Zh2En_Data["通灵学院"] = "Scholomance (SCH)"
  Zh2En_Data["通灵"] = "Scholomance (SCH)"
  Zh2En_Data["死亡矿井"] = "Deadmines (VC)"
  Zh2En_Data["矿井"] = "Deadmines (VC)"
  Zh2En_Data["影牙城堡"] = "Shadowfang Keep (SFK)"
  Zh2En_Data["影牙"] = "Shadowfang Keep (SFK)"
  Zh2En_Data["奥达曼"] = "Uldaman (UDM)"
  Zh2En_Data["黑石深渊"] = "Blackrock Depths (BRD)"
  Zh2En_Data["深渊"] = "Blackrock Depths (BRD)"
  Zh2En_Data["黑石塔上层"] = "Uper Blackrock Spirits (UBRS) (T2)"
  Zh2En_Data["黑上"] = "Uper Blackrock Spirits (UBRS) (T2)"
  Zh2En_Data["黑石塔下层"] = "Lower Blockrock Spirits (LBRS) (T1)"
  Zh2En_Data["黑下"] = "Lower Blockrock Spirits (LBRS) (T1)"
  Zh2En_Data["暴风城监狱"] = "The Stockades (Stockade)"
  Zh2En_Data["监狱"] = "The Stockades (Stockade)"
  Zh2En_Data["沉没的神庙"] = "Temple of Atal'Hakkar (The Sunken Temple) (ST)"
  Zh2En_Data["神庙"] = "Temple of Atal'Hakkar (The Sunken Temple) (ST)"
  Zh2En_Data["黑暗深渊"] = "Blackfathom Deeps (BFD)"
  Zh2En_Data["怒焰裂谷"] = "Ragefire Chasm (RFD)"
  Zh2En_Data["怒焰"] = "Ragefire Chasm (RFD)"
  Zh2En_Data["哀嚎洞穴"] = "Wailing Caverns (WC)"
  Zh2En_Data["哀嚎"] = "Wailing Caverns (WC)"
  Zh2En_Data["玛拉顿"] = "Mauradon (Mauradon)"
  Zh2En_Data["厄运之槌"] = "Dire Maul (DM)"
  Zh2En_Data["厄运"] = "Dire Maul (DM)"
  Zh2En_Data["剃刀沼泽"] = "Razorfen Kraul (RFK)"
  Zh2En_Data["沼泽"] = "Razorfen Kraul (RFK)"
  Zh2En_Data["剃刀高地"] = "Razorfen Downs (RFD)"
  Zh2En_Data["高地"] = "Razorfen Downs (RFD)"
  Zh2En_Data["祖尔法拉克"] = "Zul'Farrak (ZF)"
  Zh2En_Data["祖法"] = "Zul'Farrak (ZF)"
  Zh2En_Data["祖尔格拉布"] = "Zul'Gurub (ZG)"
  Zh2En_Data["祖格"] = "Zul'Gurub (ZG)"
  Zh2En_Data["安其拉"] = "Ahn'Qiraj (AQ)"
  Zh2En_Data["安其拉神庙"] = "Temple of Ahn'Qiraj (TAQ)"
  Zh2En_Data["安其拉废墟"] = "Ruins of Ahn'Qiraj (RAQ)"
  Zh2En_Data["废墟"] = "Ruins of Ahn'Qiraj (RAQ)"
  Zh2En_Data["熔核之心"] = "Molten Core (MC)"
  Zh2En_Data["黑翼之巢"] = "Black Wing Lair (BWL)"
  Zh2En_Data["黑翼"] = "Black Wing Lair (BWL)"
  Zh2En_Data["纳克萨玛斯"] = "Naxxramas (NAXX)"

  -- Leather
  Zh2En_Data["中毛皮"] = "Medium Hide"
  Zh2En_Data["轻毛皮"] = "Light Hide"
  Zh2En_Data["熟化中毛皮"] = "Cured Medium Hide"
  Zh2En_Data["熟化重毛皮"] = "Cured Heavy Hide"
  Zh2En_Data["中皮"] = "Medium Leather"
  Zh2En_Data["重毛皮"] = "Heavy Hide"
  Zh2En_Data["破烂的皮革"] = "Ruined Leather Scraps"
  Zh2En_Data["重皮"] = "Heavy Leather"
  Zh2En_Data["熟化轻毛皮"] = "Cured Light Hide"
  Zh2En_Data["轻皮"] = "Light Leather"
  Zh2En_Data["厚皮"] = "Thick Leather"
  Zh2En_Data["薄科多兽皮"] = "Thin Kodo Leather"
  Zh2En_Data["迅猛龙的外皮"] = "Raptor Hide"
  Zh2En_Data["飞蛇鳞片"] = "Deviate Scale"
  Zh2En_Data["完美的飞蛇鳞片"] = "Perfect Deviate Scale"
  Zh2En_Data["粘糊糊的鱼人鳞片"] = "Slimy Murloc Scale"
  Zh2En_Data["细长的尾羽"] = "Long Tail Feather"
  Zh2En_Data["盐"] = "Salt"
  Zh2En_Data["黑色雏龙鳞片"] = "Black Whelp Scale"
  Zh2En_Data["厚鱼人鳞片"] = "Thick Murloc Scale"
  Zh2En_Data["暗影猎豹毛皮"] = "Shadowcat Hide"
  Zh2En_Data["蝎壳"] = "Scorpid Scale"
  Zh2En_Data["龟壳"] = "Turtle Scale"
  Zh2En_Data["乌黑的羽毛"] = "Jet Black Feather"
  Zh2En_Data["破碎的龙鳞"] = "Worn Dragonscale"
  Zh2En_Data["厚毛皮"] = "Thick Hide"
  Zh2En_Data["石中盐"] = "Deeprock Salt"
  Zh2En_Data["硬甲毛皮"] = "Rugged Hide"
  Zh2En_Data["硬甲皮"] = "Rugged Leather"
  Zh2En_Data["厚狼皮"] = "Thick Wolfhide"
  Zh2En_Data["魔化皮"] = "Enchanted Leather"
  Zh2En_Data["厚蝎鳞"] = "Heavy Scorpid Scale"
  Zh2En_Data["精炼石中盐"] = "Refined Deeprock Salt"
  Zh2En_Data["熟化厚毛皮"] = "Cured Thick Hide"
  Zh2En_Data["奥妮克希亚鳞片"] = "Scale of Onyxia"
  Zh2En_Data["绿龙鳞片"] = "Green Dragonscale"
  Zh2En_Data["红龙鳞片"] = "Red Dragonscale"
  Zh2En_Data["蓝龙鳞片"] = "Blue Dragonscale"
  Zh2En_Data["黑龙鳞片"] = "Black Dragonscale"
  Zh2En_Data["霜刃豹皮革"] = "Frostsaber Leather"
  Zh2En_Data["绿色幼龙鳞片"] = "Green Whelp Scale"
  Zh2En_Data["铁羽毛"] = "Ironfeather"
  Zh2En_Data["熔火犬皮"] = "Core Leather"
  Zh2En_Data["战熊皮"] = "Warbear Leather"
  Zh2En_Data["奇美拉皮革"] = "Chimera Leather"
  Zh2En_Data["原始蝙蝠皮"] = "Primal Bat Leather"
  Zh2En_Data["熟化毛皮"] = "Cured Rugged Hide"
  Zh2En_Data["魔暴龙皮"] = "Devilsaur Leather"
  Zh2En_Data["梦幻龙鳞"] = "Dreamscale"
  Zh2En_Data["异种虫几丁质"] = "Silithid Chitin"
  Zh2En_Data["原始虎皮"] = "Primal Tiger Leather"
  Zh2En_Data["重型异种蝎甲壳"] = "Heavy Silithid Carapace"
  Zh2En_Data["结缔皮"] = "Knothide Leather"
  Zh2En_Data["重结缔皮"] = "Heavy Knothide Leather"
  Zh2En_Data["结缔皮碎片"] = "Knothide Leather Scraps"
  Zh2En_Data["水晶能量皮革"] = "Crystal Infused Leather"
  Zh2En_Data["厚裂蹄牛皮"] = "Thick Clefthoof Leather"
  Zh2En_Data["魔皮"] = "Fel Hide"
  Zh2En_Data["眼镜蛇鳞片"] = "Cobra Scales"
  Zh2En_Data["风鳞"] = "Wind Scales"
  Zh2En_Data["虚空龙鳞"] = "Nether Dragonscales"
  Zh2En_Data["轻型异种虫壳"] = "Light Silithid Carapace"
  Zh2En_Data["魔鳞"] = "Fel Scales"


  -- Cloth
  Zh2En_Data["丝绸卷"] = "Bolt of Silk Cloth"
  Zh2En_Data["蜘蛛丝"] = "Spider's Silk"
  Zh2En_Data["毛布卷"] = "Bolt of Woolen Cloth"
  Zh2En_Data["亚麻布"] = "Linen Cloth"
  Zh2En_Data["粗线"] = "Coarse Thread"
  Zh2En_Data["细线"] = "Fine Thread"
  Zh2En_Data["毛料"] = "Wool Cloth"
  Zh2En_Data["丝线"] = "Silken Thread"
  Zh2En_Data["丝绸"] = "Silk Cloth"
  Zh2En_Data["亚麻布卷"] = "Bolt of Linen Cloth"
  Zh2En_Data["粗蜘蛛丝"] = "Thick Spider's Silk"
  Zh2En_Data["魔纹布卷"] = "Bolt of Mageweave"
  Zh2En_Data["魔纹布"] = "Mageweave Cloth"
  Zh2En_Data["符文布卷"] = "Bolt of Runecloth"
  Zh2En_Data["暗影蛛丝"] = "Shadow Silk"
  Zh2En_Data["铁网蛛丝"] = "Ironweb Spider Silk"
  Zh2En_Data["灵纹布卷"] = "Bolt of Netherweave"
  Zh2En_Data["粗丝线"] = "Heavy Silken Thread"
  Zh2En_Data["恶魔布"] = "Felcloth"
  Zh2En_Data["月布"] = "Mooncloth"
  Zh2En_Data["符文线"] = "Rune Thread"
  Zh2En_Data["魔化灵纹布卷"] = "Bolt of Imbued Netherweave"
  Zh2En_Data["灵魂布卷"] = "Bolt of Soulcloth"
  Zh2En_Data["原始月布"] = "Primal Mooncloth"
  Zh2En_Data["灵网蜘蛛丝"] = "Netherweb Spider Silk"
  Zh2En_Data["暗影布"] = "Shadowcloth"
  Zh2En_Data["魔法布"] = "Spellcloth"
  Zh2En_Data["符文布"] = "Runecloth"
  Zh2En_Data["灵纹布"] = "Netherweave Cloth"


  -- Part
  Zh2En_Data["一把螺栓"] = "Handful of Copper Bolts"
  Zh2En_Data["高速青铜齿轮"] = "Whirring Bronze Gizmo"
  Zh2En_Data["灯油"] = "Flask of Oil"
  Zh2En_Data["烈性火药"] = "Heavy Blasting Powder"
  Zh2En_Data["损坏的调节器"] = "Copper Modulator"
  Zh2En_Data["劣质火药"] = "Rough Blasting Powder"
  Zh2En_Data["青铜框架"] = "Bronze Framework"
  Zh2En_Data["青铜管"] = "Bronze Tube"
  Zh2En_Data["粗制火药粉"] = "Coarse Blasting Powder"
  Zh2En_Data["铁棒"] = "Iron Strut"
  Zh2En_Data["铁扣环"] = "Iron Buckle"
  Zh2En_Data["发条式同步协调陀螺仪"] = "Gyrochronatom"
  Zh2En_Data["保险丝"] = "Fused Wiring"
  Zh2En_Data["秘银杆"] = "Inlaid Mithril Cylinder"
  Zh2En_Data["地精火箭燃油"] = "Goblin Rocket Fuel"
  Zh2En_Data["沉重的树干"] = "Heavy Stock"
  Zh2En_Data["银触媒"] = "Silver Contact"
  Zh2En_Data["侏儒微调器"] = "Gyromatic Micro-Adjustor"
  Zh2En_Data["实心炸药"] = "Solid Blasting Powder"
  Zh2En_Data["弯曲的铜管"] = "Copper Tube"
  Zh2En_Data["黄金能量核心"] = "Gold Power Core"
  Zh2En_Data["秘银管"] = "Mithril Tube"
  Zh2En_Data["不牢固的扳机"] = "Unstable Trigger"
  Zh2En_Data["秘银外壳"] = "Mithril Casing"
  Zh2En_Data["致密炸药粉"] = "Dense Blasting Powder"
  Zh2En_Data["瑟银管"] = "Thorium Tube"
  Zh2En_Data["精密奥金转换器"] = "Delicate Arcanite Converter"
  Zh2En_Data["墨水"] = "Engineer's Ink"
  Zh2En_Data["真银变压器"] = "Truesilver Transformer"
  Zh2En_Data["魔铁外壳"] = "Fel Iron Casing"
  Zh2En_Data["元素炸药粉"] = "Elemental Blasting Powder"
  Zh2En_Data["瑟银零件"] = "Thorium Widget"
  Zh2En_Data["魔铁螺丝"] = "Handful of Fel Iron Bolts"
  Zh2En_Data["精金框架"] = "Adamantite Frame"
  Zh2En_Data["硬化精金管"] = "Hardened Adamantite Tube"
  Zh2En_Data["氪金能量核心"] = "Khorium Power Core"
  Zh2En_Data["魔钢稳定器"] = "Felsteel Stabilizer"
  Zh2En_Data["冰霜冲击雷管"] = "Icy Blasting Primers"
  Zh2En_Data["木柴"] = "Wooden Stock"


  -- Explosive
  Zh2En_Data["重磅青铜炸弹"] = "Big Bronze Bomb"
  Zh2En_Data["铁皮手雷"] = "Iron Grenade"
  Zh2En_Data["劣质炸药"] = "Rough Dynamite"
  Zh2En_Data["小型青铜炸弹"] = "Small Bronze Bomb"
  Zh2En_Data["大型铜壳炸弹"] = "Large Copper Bomb"
  Zh2En_Data["小型爆盐炸弹"] = "Small Seaforium Charge"
  Zh2En_Data["烈性炸药"] = "Heavy Dynamite"
  Zh2En_Data["粗制炸药"] = "Coarse Dynamite"
  Zh2En_Data["劣质铜壳炸弹"] = "Rough Copper Bomb"
  Zh2En_Data["自爆绵羊"] = "Explosive Sheep"
  Zh2En_Data["简易投掷炸弹"] = "Ez-Thro Dynamite"
  Zh2En_Data["大型爆盐炸弹"] = "Large Seaforium Charge"
  Zh2En_Data["地精暗雷"] = "Goblin Land Mine"
  Zh2En_Data["重磅铁制炸弹"] = "Big Iron Bomb"
  Zh2En_Data["秘银破片炸弹"] = "Mithril Frag Bomb"
  Zh2En_Data["闪光雷"] = "Flash Bomb"
  Zh2En_Data["地精工兵炸药"] = "Goblin Sapper Charge"
  Zh2En_Data["实心炸弹"] = "Solid Dynamite"
  Zh2En_Data["大炸弹"] = "The Big One"
  Zh2En_Data["奥术炸弹"] = "Arcane Bomb"
  Zh2En_Data["黑铁炸弹"] = "Dark Iron Bomb"
  Zh2En_Data["瑟银手榴弹"] = "Thorium Grenade"
  Zh2En_Data["致密炸弹"] = "Dense Dynamite"
  Zh2En_Data["强力爆盐炸弹"] = "Powerful Seaforium Charge"
  Zh2En_Data["魔铁炸弹"] = "Fel Iron Bomb"
  Zh2En_Data["精金手雷"] = "Adamantite Grenade"
  Zh2En_Data["简易投掷炸弹 II"] = "Ez-Thro Dynamite II"
  Zh2En_Data["高爆炸弹"] = "Hi-Explosive Bomb"
  Zh2En_Data["元素爆盐炸弹"] = "Elemental Seaforium Charge"
  Zh2En_Data["更大的炸弹"] = "The Bigger One"
  Zh2En_Data["超级神风炸药"] = "Super Sapper Charge"
  Zh2En_Data["侏儒喷火炮台"] = "Gnomish Flame Turret"
  Zh2En_Data["冰霜手雷"] = "Frost Grenade"


  -- Device
  Zh2En_Data["便携式青铜迫击炮"] = "Portable Bronze Mortar"
  Zh2En_Data["退化射线"] = "Discombobulator Ray"
  Zh2En_Data["普通瞄准镜"] = "Standard Scope"
  Zh2En_Data["联合收割机组件"] = "Compact Harvest Reaper Kit"
  Zh2En_Data["活动假人"] = "Target Dummy"
  Zh2En_Data["寒冰偏斜器"] = "Ice Deflector"
  Zh2En_Data["粗制瞄准镜"] = "Crude Scope"
  Zh2En_Data["火焰偏斜器"] = "Flame Deflector"
  Zh2En_Data["精确瞄准镜"] = "Accurate Scope"
  Zh2En_Data["高级假人"] = "Advanced Target Dummy"
  Zh2En_Data["精制望远镜"] = "Ornate Spyglass"
  Zh2En_Data["报废的起搏器"] = "Ruined Jumper Cables"
  Zh2En_Data["致命瞄准镜"] = "Deadly Scope"
  Zh2En_Data["炸弹宠物"] = "Pet Bombling"
  Zh2En_Data["发条娃娃"] = "Lil' Smoky"
  Zh2En_Data["筛盐器"] = "Salt Shaker"
  Zh2En_Data["狙击瞄准镜"] = "Sniper Scope"
  Zh2En_Data["机械修理包"] = "Mechanical Repair Kit"
  Zh2En_Data["水下诱鱼器"] = "Aquadynamic Fish Attractor"
  Zh2En_Data["雪王9000型"] = "Snowmaster 9000"
  Zh2En_Data["比兹尼克247x128精确瞄准镜"] = "Biznicks 247x128 Accurascope"
  Zh2En_Data["修理机器人74A型"] = "Field Repair Bot 74A"
  Zh2En_Data["地精起搏器XL型"] = "Goblin Jumper Cables XL"
  Zh2En_Data["蒸汽车控制器"] = "Steam Tonk Controller"
  Zh2En_Data["侏儒报警机器人"] = "Gnomish Alarm-O-Bot"
  Zh2En_Data["世界放大器"] = "World Enlarger"
  Zh2En_Data["被摧毁的地精起搏器XL型"] = "Ruined Jumper Cables XL"
  Zh2En_Data["精金瞄准镜"] = "Adamantite Scope"
  Zh2En_Data["高级活动假人"] = "Masterwork Target Dummy"
  Zh2En_Data["氪金瞄准镜"] = "Khorium Scope"
  Zh2En_Data["气阀微粒提取器"] = "Zapthrottle Mote Extractor"
  Zh2En_Data["打架机器人"] = "Crashin' Thrashin' Robot"
  Zh2En_Data["稳定恒金瞄准镜"] = "Stabilized Eternium Scope"
  Zh2En_Data["地精坦克控制器"] = "Goblin Tonk Controller"
  Zh2En_Data["侏儒坦克控制器"] = "Gnomish Tonk Controller"
  Zh2En_Data["裂开的坦克控制器"] = "Battered Steam Tonk Controller"
  Zh2En_Data["远程邮件终端"] = "Remote Mail Terminal"
  Zh2En_Data["飞行器"] = "Flying Machine Control"
  Zh2En_Data["涡轮加速飞行器"] = "Turbo-Charged Flying Machine Control"
  Zh2En_Data["打架赛车控制器"] = "Crashin' Thrashin' Racer Controller"
  Zh2En_Data["战地修理机器人110G"] = "Field Repair Bot 110G"


  -- Metal & Stone
  Zh2En_Data["铁矿石"] = "Iron Ore"
  Zh2En_Data["青铜锭"] = "Bronze Bar"
  Zh2En_Data["劣质的石头"] = "Rough Stone"
  Zh2En_Data["铜锭"] = "Copper Bar"
  Zh2En_Data["金矿石"] = "Gold Ore"
  Zh2En_Data["锡矿石"] = "Tin Ore"
  Zh2En_Data["沉重的石头"] = "Heavy Stone"
  Zh2En_Data["粗糙的石头"] = "Coarse Stone"
  Zh2En_Data["铜矿石"] = "Copper Ore"
  Zh2En_Data["粗制砂轮"] = "Coarse Grinding Stone"
  Zh2En_Data["劣质砂轮"] = "Rough Grinding Stone"
  Zh2En_Data["重砂轮"] = "Heavy Grinding Stone"
  Zh2En_Data["锡锭"] = "Tin Bar"
  Zh2En_Data["铁锭"] = "Iron Bar"
  Zh2En_Data["银锭"] = "Silver Bar"
  Zh2En_Data["金锭"] = "Gold Bar"
  Zh2En_Data["银矿石"] = "Silver Ore"
  Zh2En_Data["秘银矿石"] = "Mithril Ore"
  Zh2En_Data["钢锭"] = "Steel Bar"
  Zh2En_Data["秘银锭"] = "Mithril Bar"
  Zh2En_Data["真银锭"] = "Truesilver Bar"
  Zh2En_Data["真银矿石"] = "Truesilver Ore"
  Zh2En_Data["坚固的砂轮"] = "Solid Grinding Stone"
  Zh2En_Data["瑟银矿石"] = "Thorium Ore"
  Zh2En_Data["煤块"] = "Coal"
  Zh2En_Data["黑铁矿石"] = "Dark Iron Ore"
  Zh2En_Data["坚固的石头"] = "Solid Stone"
  Zh2En_Data["黑铁锭"] = "Dark Iron Bar"
  Zh2En_Data["厚重的石头"] = "Dense Stone"
  Zh2En_Data["瑟银锭"] = "Thorium Bar"
  Zh2En_Data["致密砂轮"] = "Dense Grinding Stone"
  Zh2En_Data["魔化瑟银锭"] = "Enchanted Thorium Bar"
  Zh2En_Data["守护之石"] = "Guardian Stone"
  Zh2En_Data["萨弗隆铁锭"] = "Sulfuron Ingot"
  Zh2En_Data["奥金锭"] = "Arcanite Bar"
  Zh2En_Data["魔化源质锭"] = "Elementium Bar"
  Zh2En_Data["源质铸块"] = "Elementium Ore"
  Zh2En_Data["小块黑曜石碎片"] = "Small Obsidian Shard"
  Zh2En_Data["魔铁矿石"] = "Fel Iron Ore"
  Zh2En_Data["精金矿石"] = "Adamantite Ore"
  Zh2En_Data["氪金矿石"] = "Khorium Ore"
  Zh2En_Data["大块黑曜石碎片"] = "Large Obsidian Shard"
  Zh2En_Data["恒金矿石"] = "Eternium Ore"
  Zh2En_Data["精金锭"] = "Adamantite Bar"
  Zh2En_Data["元素助熔剂"] = "Elemental Flux"
  Zh2En_Data["恒金锭"] = "Eternium Bar"
  Zh2En_Data["魔铁锭"] = "Fel Iron Bar"
  Zh2En_Data["魔钢锭"] = "Felsteel Bar"
  Zh2En_Data["氪金锭"] = "Khorium Bar"
  Zh2En_Data["硬化氪金"] = "Hardened Khorium"
  Zh2En_Data["硬化精金锭"] = "Hardened Adamantite Bar"


  -- Meet
  Zh2En_Data["硬秃鹫肉"] = "Tough Condor Meat"
  Zh2En_Data["秃鹫肉条"] = "Stringy Vulture Meat"
  Zh2En_Data["血牙野猪的头"] = "Goretusk Snout"
  Zh2En_Data["香脆蜘蛛肉"] = "Crisp Spider Meat"
  Zh2En_Data["狼肋排"] = "Lean Wolf Flank"
  Zh2En_Data["血牙野猪的肝"] = "Goretusk Liver"
  Zh2En_Data["鱼人的眼球"] = "Murloc Eye"
  Zh2En_Data["粘糊的蜘蛛腿"] = "Gooey Spider Leg"
  Zh2En_Data["鱼人的鳍"] = "Murloc Fin"
  Zh2En_Data["大块野猪肉"] = "Chunk of Boar Meat"
  Zh2En_Data["巨型血牙野猪头"] = "Great Goretusk Snout"
  Zh2En_Data["暴风城特产调料"] = "Stormwind Seasoning Herbs"
  Zh2En_Data["山狗肉"] = "Coyote Meat"
  Zh2En_Data["多汁狼肉"] = "Stringy Wolf Meat"
  Zh2En_Data["猪排"] = "Boar Ribs"
  Zh2En_Data["猪大肠"] = "Boar Intestines"
  Zh2En_Data["蟹肉"] = "Crawler Meat"
  Zh2En_Data["蟹爪"] = "Crawler Claw"
  Zh2En_Data["峭壁野猪肋排"] = "Crag Boar Rib"
  Zh2En_Data["蜘蛛的毒液"] = "Spider Ichor"
  Zh2En_Data["鳄鱼肉"] = "Crocolisk Meat"
  Zh2En_Data["秃鹫的翅膀"] = "Buzzard Wing"
  Zh2En_Data["熊肉"] = "Bear Meat"
  Zh2En_Data["嫩鳄鱼肉"] = "Tender Crocolisk Meat"
  Zh2En_Data["海龟肉"] = "Turtle Meat"
  Zh2En_Data["大块蚌肉"] = "Giant Clam Meat"
  Zh2En_Data["迅猛龙蛋"] = "Raptor Egg"
  Zh2En_Data["新鲜的斑点黄尾鱼"] = "Raw Spotted Yellowtail"
  Zh2En_Data["柔软的狂鱼肉"] = "Soft Frenzy Flesh"
  Zh2En_Data["科多兽的肉"] = "Kodo Meat"
  Zh2En_Data["小蜘蛛腿"] = "Small Spider Leg"
  Zh2En_Data["蝎刺"] = "Scorpid Stinger"
  Zh2En_Data["雷霆蜥蜴的尾巴"] = "Thunder Lizard Tail"
  Zh2En_Data["蚌肉"] = "Clam Meat"
  Zh2En_Data["鹿肉"] = "Stag Meat"
  Zh2En_Data["陆行鸟肉"] = "Strider Meat"
  Zh2En_Data["有腥味的蚌肉"] = "Tangy Clam Meat"
  Zh2En_Data["狮肉"] = "Lion Meat"
  Zh2En_Data["大块的熊肉"] = "Big Bear Meat"
  Zh2En_Data["新鲜的美味小鱼"] = "Raw Brilliant Smallfish"
  Zh2En_Data["新鲜的长嘴泥鳅"] = "Raw Longjaw Mud Snapper"
  Zh2En_Data["新鲜的彩鳍鱼"] = "Raw Rainbow Fin Albacore"
  Zh2En_Data["新鲜的刺须鲶鱼"] = "Raw Bristle Whisker Catfish"
  Zh2En_Data["新鲜的滑皮鲭鱼"] = "Raw Slitherskin Mackerel"
  Zh2En_Data["美味的蚌肉"] = "Zesty Clam Meat"
  Zh2En_Data["新鲜的石鳞鳕鱼"] = "Raw Rockscale Cod"
  Zh2En_Data["新鲜的洛克湖狂鱼"] = "Raw Loch Frenzy"
  Zh2En_Data["新鲜的刺脊比目鱼"] = "Raw Spinefin Halibut"
  Zh2En_Data["小蛋"] = "Small Egg"
  Zh2En_Data["迅猛龙肉"] = "Raptor Flesh"
  Zh2En_Data["虎肉"] = "Tiger Meat"
  Zh2En_Data["神秘的肉"] = "Mystery Meat"
  Zh2En_Data["红狼肉"] = "Red Wolf Meat"
  Zh2En_Data["科多兽肉"] = "Heavy Kodo Meat"
  Zh2En_Data["嫩螃蟹肉"] = "Tender Crab Meat"
  Zh2En_Data["白蜘蛛肉"] = "White Spider Meat"
  Zh2En_Data["巨蛋"] = "Giant Egg"
  Zh2En_Data["嫩狼肉"] = "Tender Wolf Meat"
  Zh2En_Data["新鲜的光滑大鱼"] = "Raw Glossy Mightfish"
  Zh2En_Data["新鲜的夏日鲈鱼"] = "Raw Summer Bass"
  Zh2En_Data["蝙蝠肉翅"] = "Meaty Bat Wing"
  Zh2En_Data["新鲜的红腮鱼"] = "Raw Redgill"
  Zh2En_Data["新鲜的夜鳞鲷鱼"] = "Raw Nightfin Snapper"
  Zh2En_Data["新鲜的银头鲑鱼"] = "Raw Mithril Head Trout"
  Zh2En_Data["新鲜的阳鳞鲑鱼"] = "Raw Sunscale Salmon"
  Zh2En_Data["黑爪龙虾"] = "Darkclaw Lobster"
  Zh2En_Data["新鲜的白鳞鲑鱼"] = "Raw Whitescale Salmon"
  Zh2En_Data["沙虫的肉"] = "Sandworm Meat"
  Zh2En_Data["新鲜的鼠尾鱼"] = "Raw Sagefish"
  Zh2En_Data["新鲜的大鼠尾鱼"] = "Raw Greater Sagefish"
  Zh2En_Data["裂开的蚌肉"] = "Jaggal Clam Meat"
  Zh2En_Data["刺鳃鲑鱼"] = "Barbed Gill Trout"
  Zh2En_Data["斑点魔尾鱼"] = "Spotted Feltail"
  Zh2En_Data["松脆蜘蛛腿"] = "Crunchy Spider Leg"
  Zh2En_Data["菲格鲁泥鱼"] = "Figluster's Mudfish"
  Zh2En_Data["赞加孢子鱼"] = "Zangarian Sporefish"
  Zh2En_Data["奇美洛克的腰肋肉"] = "Chimaerok Tenderloin"
  Zh2En_Data["冰鳞蓝鱼"] = "Icefin Bluefish"
  Zh2En_Data["金镖鱼"] = "Golden Darter"
  Zh2En_Data["狂暴龙虾"] = "Furious Crawdad"
  Zh2En_Data["月痕鹿的嫩腰肉"] = "Moongraze Stag Tenderloin"
  Zh2En_Data["蝙蝠肉"] = "Bat Flesh"
  Zh2En_Data["秃鹰肉"] = "Buzzard Meat"
  Zh2En_Data["山猫肉"] = "Lynx Meat"
  Zh2En_Data["奇怪的孢子"] = "Strange Spores"
  Zh2En_Data["掠食者的肉"] = "Ravager Flesh"
  Zh2En_Data["迁跃兽肉"] = "Warped Flesh"
  Zh2En_Data["塔布羊肉"] = "Talbuk Venison"
  Zh2En_Data["迅猛龙肋排"] = "Raptor Ribs"
  Zh2En_Data["蛇肉"] = "Serpent Flesh"
  Zh2En_Data["血鳞鲶鱼"] = "Bloodfin Catfish"
  Zh2En_Data["蜥蜴肉块"] = "Chunk o' Basilisk"
  Zh2En_Data["弯尾骨鱼"] = "Crescent-Tail Skullfish"
  Zh2En_Data["巨型太阳鱼"] = "Giant Sunfish"
  Zh2En_Data["裂蹄牛肉"] = "Clefthoof Meat"
  Zh2En_Data["基本被消化的鱼"] = "Mostly Digested Fish"
  Zh2En_Data["熊腰肉"] = "Bear Flank"


  -- Herb
  Zh2En_Data["野钢花"] = "Wild Steelbloom"
  Zh2En_Data["皇血草"] = "Kingsblood"
  Zh2En_Data["宁神花"] = "Peacebloom"
  Zh2En_Data["银叶草"] = "Silverleaf"
  Zh2En_Data["魔皇草"] = "Mageroyal"
  Zh2En_Data["跌打草"] = "Bruiseweed"
  Zh2En_Data["活根草"] = "Liferoot"
  Zh2En_Data["地根草"] = "Earthroot"
  Zh2En_Data["雨燕草"] = "Swiftthistle"
  Zh2En_Data["墓地苔"] = "Grave Moss"
  Zh2En_Data["石南草"] = "Briarthorn"
  Zh2En_Data["卡德加的胡须"] = "Khadgar's Whisker"
  Zh2En_Data["枯叶草"] = "Fadeleaf"
  Zh2En_Data["龙齿草"] = "Wintersbite"
  Zh2En_Data["金棘草"] = "Goldthorn"
  Zh2En_Data["荆棘藻"] = "Stranglekelp"
  Zh2En_Data["火焰花"] = "Firebloom"
  Zh2En_Data["紫莲花"] = "Purple Lotus"
  Zh2En_Data["野葡萄藤"] = "Wildvine"
  Zh2En_Data["阿尔萨斯之泪"] = "Arthas' Tears"
  Zh2En_Data["盲目草"] = "Blindweed"
  Zh2En_Data["太阳草"] = "Sungrass"
  Zh2En_Data["幽灵菇"] = "Ghost Mushroom"
  Zh2En_Data["格罗姆之血"] = "Gromsblood"
  Zh2En_Data["梦叶草"] = "Dreamfoil"
  Zh2En_Data["黄金参"] = "Golden Sansam"
  Zh2En_Data["山鼠草"] = "Mountain Silversage"
  Zh2En_Data["哀伤苔"] = "Plaguebloom"
  Zh2En_Data["冰盖草"] = "Icecap"
  Zh2En_Data["黑莲花"] = "Black Lotus"
  Zh2En_Data["血镰刀"] = "Blood Scythe"
  Zh2En_Data["血藤"] = "Bloodvine"
  Zh2En_Data["血蓟"] = "Bloodthistle"
  Zh2En_Data["邪雾草"] = "Ragveil"
  Zh2En_Data["梦露花"] = "Dreaming Glory"
  Zh2En_Data["魔草"] = "Felweed"
  Zh2En_Data["泰罗果"] = "Terocone"
  Zh2En_Data["虚空花"] = "Netherbloom"
  Zh2En_Data["烈焰菇"] = "Flame Cap"
  Zh2En_Data["噩梦藤"] = "Nightmare Vine"
  Zh2En_Data["远古苔"] = "Ancient Lichen"
  Zh2En_Data["法力蓟"] = "Mana Thistle"
  Zh2En_Data["梦魇草"] = "Nightmare Seed"
  Zh2En_Data["魔莲花"] = "Fel Lotus"


  -- Elemental
  Zh2En_Data["大地精华"] = "Essence of Earth"
  Zh2En_Data["元素空气"] = "Elemental Air"
  Zh2En_Data["纯水之球"] = "Globe of Water"
  Zh2En_Data["元素火焰"] = "Elemental Fire"
  Zh2En_Data["火焰之心"] = "Heart of Fire"
  Zh2En_Data["元素之土"] = "Elemental Earth"
  Zh2En_Data["水之精华"] = "Essence of Water"
  Zh2En_Data["元素之水"] = "Elemental Water"
  Zh2En_Data["大地之核"] = "Core of Earth"
  Zh2En_Data["空气精华"] = "Essence of Air"
  Zh2En_Data["源生火焰"] = "Primal Fire"
  Zh2En_Data["风之气息"] = "Breath of Wind"
  Zh2En_Data["生命精华"] = "Living Essence"
  Zh2En_Data["火焰精华"] = "Essence of Fire"
  Zh2En_Data["亡灵腐液"] = "Ichor of Undeath"
  Zh2En_Data["野性之心"] = "Heart of the Wild"
  Zh2En_Data["死灵精华"] = "Essence of Undeath"
  Zh2En_Data["源生空气"] = "Primal Air"
  Zh2En_Data["源生之土"] = "Primal Earth"
  Zh2En_Data["源生暗影"] = "Primal Shadow"
  Zh2En_Data["源生之水"] = "Primal Water"
  Zh2En_Data["源生法力"] = "Primal Mana"
  Zh2En_Data["源生生命"] = "Primal Life"
  Zh2En_Data["空气微粒"] = "Mote of Air"
  Zh2En_Data["源生之能"] = "Primal Might"
  Zh2En_Data["土之微粒"] = "Mote of Earth"
  Zh2En_Data["火焰微粒"] = "Mote of Fire"
  Zh2En_Data["暗影微粒"] = "Mote of Shadow"
  Zh2En_Data["法力微粒"] = "Mote of Mana"
  Zh2En_Data["水之微粒"] = "Mote of Water"
  Zh2En_Data["生命微粒"] = "Mote of Life"


  -- Enchanting
  Zh2En_Data["次级星界精华"] = "Lesser Astral Essence"
  Zh2En_Data["强效魔法精华"] = "Greater Magic Essence"
  Zh2En_Data["符文银棒"] = "Runed Silver Rod"
  Zh2En_Data["银棒"] = "Silver Rod"
  Zh2En_Data["符文铜棒"] = "Runed Copper Rod"
  Zh2En_Data["强效星界精华"] = "Greater Astral Essence"
  Zh2En_Data["小块微光碎片"] = "Small Glimmering Shard"
  Zh2En_Data["次级魔法精华"] = "Lesser Magic Essence"
  Zh2En_Data["奇异之尘"] = "Strange Dust"
  Zh2En_Data["铜棒"] = "Copper Rod"
  Zh2En_Data["大块微光碎片"] = "Large Glimmering Shard"
  Zh2En_Data["灵魂之尘"] = "Soul Dust"
  Zh2En_Data["强效秘法精华"] = "Greater Mystic Essence"
  Zh2En_Data["次级秘法精华"] = "Lesser Mystic Essence"
  Zh2En_Data["金棒"] = "Golden Rod"
  Zh2En_Data["符文金棒"] = "Runed Golden Rod"
  Zh2En_Data["大块闪光碎片"] = "Large Glowing Shard"
  Zh2En_Data["小块闪光碎片"] = "Small Glowing Shard"
  Zh2En_Data["真银棒"] = "Truesilver Rod"
  Zh2En_Data["次级虚空精华"] = "Lesser Nether Essence"
  Zh2En_Data["强效虚空精华"] = "Greater Nether Essence"
  Zh2En_Data["小块强光碎片"] = "Small Radiant Shard"
  Zh2En_Data["符文真银棒"] = "Runed Truesilver Rod"
  Zh2En_Data["梦境之尘"] = "Dream Dust"
  Zh2En_Data["大块强光碎片"] = "Large Radiant Shard"
  Zh2En_Data["小块魔光碎片"] = "Small Brilliant Shard"
  Zh2En_Data["次级不灭精华"] = "Lesser Eternal Essence"
  Zh2En_Data["大块魔光碎片"] = "Large Brilliant Shard"
  Zh2En_Data["幻象之尘"] = "Vision Dust"
  Zh2En_Data["奥金棒"] = "Arcanite Rod"
  Zh2En_Data["符文奥金棒"] = "Runed Arcanite Rod"
  Zh2En_Data["次级巫师之油"] = "Lesser Wizard Oil"
  Zh2En_Data["幻影之尘"] = "Illusion Dust"
  Zh2En_Data["强效不灭精华"] = "Greater Eternal Essence"
  Zh2En_Data["连结水晶"] = "Nexus Crystal"
  Zh2En_Data["次级法力之油"] = "Lesser Mana Oil"
  Zh2En_Data["奥法之尘"] = "Arcane Dust"
  Zh2En_Data["强效位面精华"] = "Greater Planar Essence"
  Zh2En_Data["次级位面精华"] = "Lesser Planar Essence"
  Zh2En_Data["小块棱光碎片"] = "Small Prismatic Shard"
  Zh2En_Data["符文魔铁棒"] = "Runed Fel Iron Rod"
  Zh2En_Data["大块棱光碎片"] = "Large Prismatic Shard"
  Zh2En_Data["虚空水晶"] = "Void Crystal"
  Zh2En_Data["符文精金棒"] = "Runed Adamantite Rod"
  Zh2En_Data["符文恒金棒"] = "Runed Eternium Rod"
  Zh2En_Data["魔铁棒"] = "Fel Iron Rod"
  Zh2En_Data["精金棒"] = "Adamantite Rod"
  Zh2En_Data["恒金棒"] = "Eternium Rod"


  -- Material
  Zh2En_Data["源生虚空"] = "Primal Nether"
  Zh2En_Data["虚空漩涡"] = "Nether Vortex"


  -- Other
  Zh2En_Data["辣椒"] = "Hot Spices"
  Zh2En_Data["拳头大小的丝囊"] = "Fist-sized Spinneret"
  Zh2En_Data["小毒囊"] = "Small Venom Sac"
  Zh2En_Data["大毒囊"] = "Large Venom Sac"
  Zh2En_Data["黑色染料"] = "Black Dye"
  Zh2En_Data["绿色染料"] = "Green Dye"
  Zh2En_Data["弱效助熔剂"] = "Weak Flux"
  Zh2En_Data["红色染料"] = "Red Dye"
  Zh2En_Data["甜香料"] = "Mild Spices"
  Zh2En_Data["变色的狼心"] = "Discolored Worg Heart"
  Zh2En_Data["破碎的瓶子"] = "Leaded Vial"
  Zh2En_Data["漂白液"] = "Bleach"
  Zh2En_Data["舒心草"] = "Soothing Spices"
  Zh2En_Data["强效助熔剂"] = "Strong Flux"
  Zh2En_Data["火囊"] = "Small Flame Sac"
  Zh2En_Data["燧石和火绒"] = "Flint and Tinder"
  Zh2En_Data["灰色染料"] = "Gray Dye"
  Zh2En_Data["黄色染料"] = "Yellow Dye"
  Zh2En_Data["紫色染料"] = "Purple Dye"
  Zh2En_Data["细长的狮鹫羽毛"] = "Long Elegant Feather"
  Zh2En_Data["蓝珍珠"] = "Blue Pearl"
  Zh2En_Data["普通木柴"] = "Simple Wood"
  Zh2En_Data["小蚌壳"] = "Small Barnacled Clam"
  Zh2En_Data["锋利的爪子"] = "Sharp Claw"
  Zh2En_Data["火鳞鳝鱼"] = "Firefin Snapper"
  Zh2En_Data["硬壳蚌"] = "Thick-shelled Clam"
  Zh2En_Data["黑口鱼"] = "Oily Blackmouth"
  Zh2En_Data["黑口鱼油"] = "Blackmouth Oil"
  Zh2En_Data["大牙齿"] = "Large Fang"
  Zh2En_Data["蓝色染料"] = "Blue Dye"
  Zh2En_Data["橙色染料"] = "Orange Dye"
  Zh2En_Data["火焰之油"] = "Fire Oil"
  Zh2En_Data["纳迦鳞片"] = "Naga Scale"
  Zh2En_Data["大瓶魔精"] = "Flask of Big Mojo"
  Zh2En_Data["魔精"] = "Flask of Mojo"
  Zh2En_Data["被污染的瓶子"] = "Crystal Vial"
  Zh2En_Data["大嘴蚌壳"] = "Big-mouth Clam"
  Zh2En_Data["幻象染料"] = "Ghost Dye"
  Zh2En_Data["邪恶之爪"] = "Wicked Claw"
  Zh2En_Data["黑色硫酸盐"] = "Black Vitriol"
  Zh2En_Data["断裂的英雄之剑"] = "Broken Blade of Heroes"
  Zh2En_Data["普通的羊皮纸"] = "Blank Parchment"
  Zh2En_Data["星木"] = "Star Wood"
  Zh2En_Data["石鳞鳗"] = "Stonescale Eel"
  Zh2En_Data["正义宝珠"] = "Righteous Orb"
  Zh2En_Data["恶魔符文"] = "Demonic Rune"
  Zh2En_Data["强力魔精"] = "Powerful Mojo"
  Zh2En_Data["石鳞鱼油"] = "Stonescale Oil"
  Zh2En_Data["水晶瓶"] = "Empty Vial"
  Zh2En_Data["炼金石"] = "Alchemist's Stone"
  Zh2En_Data["电鳗"] = "Lightning Eel"
  Zh2En_Data["炽热之核"] = "Fiery Core"
  Zh2En_Data["熔岩之核"] = "Lava Core"
  Zh2En_Data["萨弗拉斯之眼"] = "Eye of Sulfuras"
  Zh2En_Data["食人魔鞣酸"] = "Ogre Tannin"
  Zh2En_Data["融化之瓶"] = "Imbued Vial"
  Zh2En_Data["幼虫酸液"] = "Larval Acid"
  Zh2En_Data["粉红染料"] = "Pink Dye"
  Zh2En_Data["极效魔精"] = "Massive Mojo"
  Zh2En_Data["巨型毒囊"] = "Huge Venom Sac"
  Zh2En_Data["黑暗符文"] = "Dark Rune"
  Zh2En_Data["熔解之语"] = "Word of Thawing"
  Zh2En_Data["灵魂精华"] = "Soul Essence"
  Zh2En_Data["雕文卷轴盒"] = "Inscribed Scrollcase"
  Zh2En_Data["冰冻符文"] = "Frozen Rune"
  Zh2En_Data["奇怪的箱子"] = "Curious Crate"
  Zh2En_Data["水银石"] = "Mercurial Stone"
  Zh2En_Data["裂纹的蚌壳"] = "Jaggal Clam"
  Zh2En_Data["面粉"] = "Simple Flour"
  Zh2En_Data["黑暗之心"] = "Heart of Darkness"
  Zh2En_Data["救赎者的炼金石"] = "Redeemer's Alchemist Stone"
  Zh2En_Data["守护者的炼金石"] = "Guardian's Alchemist Stone"
  Zh2En_Data["巫师的炼金石"] = "Sorcerer's Alchemist Stone"
  Zh2En_Data["刺客的炼金石"] = "Assassin's Alchemist Stone"
  Zh2En_Data["太阳之尘"] = "Sunmote"
  Zh2En_Data["珠宝制作工具"] = "Jeweler's Kit"

  Zh2En_addMessage("数据已加载")
end
